# Generated by Django 6.0.7 on 2026-07-22 13:14

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Key used by the frontend (header, introduction, countries, satellite, information, observations). Do not change without coordinating with the frontend.', unique=True)),
                ('section_label', models.CharField(blank=True, help_text="Small label above the title (JSON field 'section').", max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subline', models.TextField(blank=True)),
                ('text', models.TextField(blank=True, help_text='Prose. Inline HTML (links, <br/>) is allowed and rendered verbatim by the frontend.')),
            ],
            options={
                'verbose_name': 'content section',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL id used by the frontend (e.g. 'brazil').", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2 (e.g. BR).', max_length=2)),
                ('region', models.CharField(max_length=50)),
                ('report_date', models.CharField(help_text="Displayed as-is (e.g. 'March 2026').", max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('providers_authorized', models.PositiveIntegerField()),
                ('providers_operational', models.PositiveIntegerField()),
                ('card_title', models.CharField(max_length=255)),
                ('card_blurb', models.TextField()),
                ('header_info', models.TextField(help_text='One-line stats shown under the country header.')),
                ('key_finding', models.TextField()),
                ('primary_driver_label', models.CharField(max_length=100)),
                ('primary_driver_description', models.TextField()),
                ('local_presence_label', models.CharField(max_length=100)),
                ('local_presence_description', models.TextField()),
                ('competition_label', models.CharField(max_length=100)),
                ('competition_description', models.TextField()),
                ('key_gap_label', models.CharField(max_length=100)),
                ('key_gap_description', models.TextField()),
                ('quote', models.TextField(blank=True, null=True)),
                ('quote_attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField()),
                ('licensing_pathway', models.CharField(help_text="Short label (e.g. 'Fast-tracked', 'Emergency').", max_length=100)),
                ('licensing_pathway_note', models.TextField()),
                ('qos_obligations', models.BooleanField(default=False)),
                ('outage_reporting_required', models.BooleanField(default=False)),
                ('local_data_landing_mandate', models.BooleanField(default=False)),
                ('local_partner_requirement', models.BooleanField(default=False)),
                ('foreign_ownership_exception', models.BooleanField(default=False)),
                ('public_consultation', models.BooleanField(default=False)),
                ('cybersecurity_audit', models.BooleanField(default=False)),
                ('scorecard_summary_note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MapCountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Preserves the original file order.')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'map country name',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ContentSectionCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(help_text='Internal path (/satellites) or full URL.', max_length=255)),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctas', to='observatory.contentsection')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('local_entity', models.CharField(blank=True, help_text='Local subsidiary/partner, if any.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('prospective', 'Prospective'), ('authorized', 'Authorized'), ('operational', 'Operational')], max_length=20)),
                ('country', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_providers', to='observatory.country')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyLever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField()),
                ('country', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_levers', to='observatory.country')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('severity', models.CharField(choices=[('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('text', models.TextField()),
                ('country', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='observatory.country')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('provider', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=255)),
                ('date', models.CharField(help_text='YYYY-MM', max_length=10)),
                ('category', models.CharField(choices=[('contact', 'Contact'), ('licensing', 'Licensing'), ('authorization', 'Authorization'), ('launch', 'Launch')], max_length=20)),
                ('country', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='observatory.country')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
