# Generated by Django 6.0.7 on 2026-07-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='uso_rollout',
            field=models.TextField(blank=True, help_text='Universal service obligation rollout status, if any (only present for some countries).'),
        ),
    ]
