# Generated by Django 6.0.7 on 2026-07-22 13:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0002_country_uso_rollout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policylever',
            name='country',
        ),
        migrations.RemoveField(
            model_name='redflag',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='competition_description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='competition_label',
        ),
        migrations.RemoveField(
            model_name='country',
            name='cybersecurity_audit',
        ),
        migrations.RemoveField(
            model_name='country',
            name='foreign_ownership_exception',
        ),
        migrations.RemoveField(
            model_name='country',
            name='key_gap_description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='key_gap_label',
        ),
        migrations.RemoveField(
            model_name='country',
            name='licensing_pathway',
        ),
        migrations.RemoveField(
            model_name='country',
            name='licensing_pathway_note',
        ),
        migrations.RemoveField(
            model_name='country',
            name='local_data_landing_mandate',
        ),
        migrations.RemoveField(
            model_name='country',
            name='local_partner_requirement',
        ),
        migrations.RemoveField(
            model_name='country',
            name='local_presence_description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='local_presence_label',
        ),
        migrations.RemoveField(
            model_name='country',
            name='outage_reporting_required',
        ),
        migrations.RemoveField(
            model_name='country',
            name='primary_driver_description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='primary_driver_label',
        ),
        migrations.RemoveField(
            model_name='country',
            name='public_consultation',
        ),
        migrations.RemoveField(
            model_name='country',
            name='qos_obligations',
        ),
        migrations.RemoveField(
            model_name='country',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='country',
            name='quote_attribution',
        ),
        migrations.RemoveField(
            model_name='country',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='country',
            name='scorecard_summary_note',
        ),
        migrations.RemoveField(
            model_name='country',
            name='uso_rollout',
        ),
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True, help_text='Shown as active on the frontend.'),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.CharField(default='', help_text="Displayed as-is (e.g. '213.7 million').", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='primary_driver',
            field=models.CharField(default='', help_text="Short label (e.g. 'Executive Lobbying').", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='risk',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='category',
            field=models.CharField(choices=[('contact', 'Contact'), ('licensing', 'Licensing'), ('authorization', 'Authorization'), ('launch', 'Launch'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='ResearchDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('text', models.TextField()),
                ('country', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_dimensions', to='observatory.country')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(help_text='Short value. Inline HTML (<br/>) is allowed for line breaks.')),
                ('dimension', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='observatory.researchdimension')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MarketProvider',
        ),
        migrations.DeleteModel(
            name='PolicyLever',
        ),
        migrations.DeleteModel(
            name='RedFlag',
        ),
    ]
