# Generated by Django 6.0.7 on 2026-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0003_remove_policylever_country_remove_redflag_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchindicator',
            name='name',
            field=models.CharField(blank=True, help_text='Optional label shown before the value.', max_length=100),
        ),
    ]
