# Generated by Django 6.0.7 on 2026-07-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0004_alter_researchindicator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcountryname',
            name='code',
            field=models.CharField(help_text="ISO 3166-1 alpha-2 code, or a territory name when no ISO code exists (e.g. 'Somaliland').", max_length=32, unique=True),
        ),
    ]
